//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonType {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonType.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 现金不足！ 的本地化字符串。
        /// </summary>
        internal static string CashOut {
            get {
                return ResourceManager.GetString("CashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验不在运行，不允许交易！ 的本地化字符串。
        /// </summary>
        internal static string ExperimentNotRun {
            get {
                return ResourceManager.GetString("ExperimentNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 股票数量不足！ 的本地化字符串。
        /// </summary>
        internal static string InsufficientStocks {
            get {
                return ResourceManager.GetString("InsufficientStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查交易数量！ 的本地化字符串。
        /// </summary>
        internal static string TradeStocksOut {
            get {
                return ResourceManager.GetString("TradeStocksOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经交易，不得重复交易 的本地化字符串。
        /// </summary>
        internal static string TradeTwice {
            get {
                return ResourceManager.GetString("TradeTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在，不得交易 的本地化字符串。
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已破产，感谢您的参与！ 的本地化字符串。
        /// </summary>
        internal static string UserRuin {
            get {
                return ResourceManager.GetString("UserRuin", resourceCulture);
            }
        }
    }
}
